title: "Quels usages pour les Jupyter Notebooks en Sciences Sociales?"
author: "POPINEAU Maxime"
logo: "logo.png"
execute:
  execute_notebooks: force
bibtex_bibfiles:
  - "references.bib"
repository:
  url: "https://github.com/MaximePop/Jupyter-Notebook-in-social-science"
launch_buttons:
  binderhub_url: "https://hub.ovh2.mybinder.org/user/maximepop-testjupyter-uk1q7dc4/lab/workspaces/auto-J/tree/notebooks.ipynb"
html:
repository:
  url: "https://github.com/MaximePop/Jupyter-Notebook-in-social-science"
  html:
  use_repository_button: true
repository:
  url: "https://github.com/MaximePop/Jupyter-Notebook-in-social-science"
  html:
  use_issues_button: true
repository:
  url: "https://github.com/MaximePop/Jupyter-Notebook-in-social-science"
  html:
  use_edit_page_button: true
sphinx:
  config:
    html_js_files:
      - "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
