# In _config.yml
title: Quels usages pour les Jupyter Notebooks en Sciences Sociales ?
author: POPINEAU Maxime
logo: logo.png
execute:
  execute_notebooks: force
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
repository:
  url: https://github.com/{MaximePop/Jupyter-Notebook-in-social-science}
repository:
  url: https://github.com/{MaximePop/Jupyter-Notebook-in-social-science}
html:
  use_repository_button: true
repository:
  url: https://github.com/{MaximePop/Jupyter-Notebook-in-social-science}
html:
  use_issues_button: true
repository:
  url: https://github.com/{MaximePop/Jupyter-Notebook-in-social-science}
  path_to_book: path/to/your/book  # An optional path to your book, defaults to repo root
  branch: yourbranch  # An optional branch, defaults to `master`
html:
  use_edit_page_button: true
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js